name: DEKUVE
on:
  push:
    branches:
      - 'main'
    paths-ignore:
      - '.editorconfig'
      - 'leiame.md'
      - 'readme.md'
      - '*.jpg'
      - '*.png'
      - '*.svg'
      - '_config.yml'
  schedule:
    - cron:  '0 */12 * * *'
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: DEKUVE build
        run: bash build-dekuve.sh
      - name: ISO upload
        uses: actions/upload-artifact@v3
        with:
          name: dekuve
          path: /tmp/dekuve/dekuve*.iso